# Generated by Django 4.2.4 on 2024-01-03 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0002_task_chosen_alter_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='key',
        ),
    ]
