# Generated by Django 4.2.4 on 2024-01-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thing', '0003_rename_id_task_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('point', models.IntegerField()),
                ('accepted', models.BooleanField()),
            ],
        ),
    ]
